compatibility_date = "2021-09-12"
type = 'webpack'
usage_model = ''
target_type = "webpack"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "murrr-space-dev"
usage_model = ''
workers_dev = true
route = 'dev.murrr.space/*'

[env.production]
name = "murrr-space"
workers_dev = false
route = 'murrr.space/*'

