type = 'webpack'
usage_model = ''
target_type = "webpack"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "murrr-space"
usage_model = ''
workers_dev = true

[env.production]
name = "murrr-space"
workers_dev = false
route = 'murrr.space/*'

